### ISSUE TITLE
doesn't lift the tracks

### ISSUE THREAD

**Issue by LavrenovRoman** [tu-darmstadt-ros-pkg/vehicle_controller#1]
Hello!
In your video https://www.youtube.com/watch?v=dHWFviA2S3Е robot raises and lowers the front tracks, but implementing the modules of your package I can not do it. The robot (spawn_obelix_ugv) moves but doesn't lift the tracks. 
Functionality is not recorded in the GIT or am I doing something wrong?
Thanks:)

**Comment by skohlbr** [comment]
This is not a vehicle controller issue. You can open another one in https://github.com/tu-darmstadt-ros-pkg/hector_tracked_vehicles_common/.
