### ISSUE TITLE
path smooth module for hector exploration

### ISSUE THREAD

**Issue by lukelu520** [tu-darmstadt-ros-pkg/vehicle_controller#2]
Dear vehicle_controller friends,

We are adding ps3d.h & ps3d.cpp for path smoothing to hector_exploration_planner. But we are very new with the module and the interface between them. For exmaple, the smooth function in ps3d takes deque_vec3 const & in_path in order to compute a smoothed path, while hector_exploration_planner uses std::vector<geometry_msgs::PoseStamped> &plan to get trajectory. 

We were wondering if you have any idea to integrate (or transfer) the path smooth to hector_exploration. Hope to hear your expertise.

Thanks,
-- Luke

**Comment by StefanFabian** [comment]
I don't know why a deque was chosen, a vector would have been a better choice but you can easily convert between the two.

**Comment by lukelu520** [comment]
Problem solved after incorporating ps3d with hector_exploration_planner and hector_exploration_node.
Reference: a closed [issue](https://github.com/tu-darmstadt-ros-pkg/hector_navigation/issues/30) in hector_navigation.

Thanks,
-- Luke
